name: CSAF Extensions Test (CSAF 2.1)

on:
  push:
    paths:
      - 'csaf_2.1/**'
  pull_request:
    paths:
      - 'csaf_2.1/**'

jobs:
  metaschema-test:
    runs-on: ubuntu-latest
    name: Test Extension JSON schemas against extension-metaschema
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Prepare environment
      run: |
        sudo apt-get remove python3-jsonschema
        sudo apt-get update -q && sudo apt-get install -y --no-install-recommends -qq \
          python3 \
          python3-simplejson \
          python3-jsonpath-rw \
          python3-pip \
          python3-setuptools \
          python3-wheel
        pip3 install jsonschema[format]
    - name: Check jsonschema version
      run: python3 -c "from importlib.metadata import version; print(version('jsonschema'))"
    - name: Test extensions in extension/data/valid/*/*.json
      run: ./csaf_2.1/test/extension/run_tests.sh ./csaf_2.1/test/extension/data/valid/*/*-content_*.json
    - name: Test extensions in extension/data/valid/*/*.json
      run: ./csaf_2.1/test/extension/run_invalid_tests.sh ./csaf_2.1/test/extension/data/invalid/*/*-content_*.json
