name: Validator Data Test (CSAF 2.0)

on: 
  push:
    paths:
      - 'csaf_2.0/**'
  pull_request:
    paths:
      - 'csaf_2.0/**'

jobs:
  validator-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Prepare environment
      run: |
        sudo apt-get remove python3-jsonschema
        sudo apt-get update -q && sudo apt-get install -y --no-install-recommends -qq \
          python3 \
          python3-simplejson \
          python3-jsonpath-rw \
          python3-pip \
          python3-setuptools \
          python3-wheel
        pip3 install jsonschema[format]
    - name: Check jsonschema version
      run: python3 -c "from importlib.metadata import version; print(version('jsonschema'))"
    - name: Test validator/data/mandatory against schema
      run: ./csaf_2.0/test/validator/run_tests.sh mandatory
    - name: Test validator/data/optional against schema
      run: ./csaf_2.0/test/validator/run_tests.sh optional
    - name: Test validator/data/informative against schema
      run: ./csaf_2.0/test/validator/run_tests.sh informative

    - name: Test validator/data/testcases.json against testcase schema
      run: ./csaf_2.0/test/validator/check_testcases.sh