name: CSAF Filenames Test

on: [push, pull_request]

jobs:
  filename-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test filenames of CSAF filename test files in filenames/data/valid/*.json
      run: ./csaf_2.0/test/filenames/run_tests.sh ./csaf_2.0/test/filenames/data/valid/*.json
    - name: Test filenames of CSAF examples
      run: ./csaf_2.0/test/filenames/run_tests.sh ./csaf_2.0/examples/csaf/*.json
    - name: Test filenames of CSAF examples - profile specific folders 
      run: ./csaf_2.0/test/filenames/run_tests.sh ./csaf_2.0/examples/csaf/csaf_*/*.json
    - name: Test filenames of CSAF test files in validator/data/mandatory
      run: ./csaf_2.0/test/filenames/run_tests.sh ./csaf_2.0/test/validator/data/mandatory/*.json
    - name: Test filenames of CSAF test files in validator/data/optional 
      run: ./csaf_2.0/test/filenames/run_tests.sh ./csaf_2.0/test/validator/data/optional/*.json
    - name: Test filenames of CSAF test files in validator/data/informative
      run: ./csaf_2.0/test/filenames/run_tests.sh ./csaf_2.0/test/validator/data/informative/*.json
