name: Validator Data Test

on: [push, pull_request]

jobs:
  validator-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        sudo apt-get remove python3-jsonschema
        sudo apt-get update -q && apt-get install -y --no-install-recommends -qq \
          python3 \
          python3-simplejson \
          python3-jsonpath-rw \
          python3-pip \
          python3-setuptools \
          python3-wheel
        pip3 install jsonschema[format]
    - name: Test validator/data/mandatory against schema
      run: ./csaf_2.0/test/validator/run_tests.sh mandatory
    - name: Test validator/data/optional against schema
      run: ./csaf_2.0/test/validator/run_tests.sh optional
    - name: Test validator/data/informative against schema
      run: ./csaf_2.0/test/validator/run_tests.sh informative
